[project]
name = "idun-agent-manager"
version = "0.1.0"
description = ""
authors = [
    {name = "Geoffrey HARRAZI",email = "geoffreyharrazi@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn[standard] (>=0.34.2,<0.35.0)",
    "langgraph (>=0.4.8,<0.5.0)",
    "langgraph-checkpoint-sqlite (>=2.0.10,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
