[tool.poetry]
name = "idun-agent-platform"
version = "0.1.0"
description = "Monorepo for Idun Agent Platform"
authors = ["Geoffrey HARRAZI <geoffreyharrazi@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
idun-agent-engine = { path = "libs/idun_agent_engine", develop = true }

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
black = "^24.8.0"
pre-commit = "^3.8.0"
mypy = "^1.10.0"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
types-PyYAML = "^6.0.12.20240808"
pyright = "^1.1.404"
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.39"
mkdocstrings = {extras = ["python"], version = "^0.26.2"}
mkdocs-gen-files = "^0.5.0"
mkdocs-autorefs = "^1.2.0"
mkdocs-include-markdown-plugin = "^7.0.0"
mkdocs-redirects = "^1.2.1"
mkdocs-section-index = "^0.3.9"
mkdocs-git-revision-date-localized-plugin = "^1.2.6"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
