# Ruff configuration (repo-wide)
# Centralized lint settings for the monorepo.

target-version = "py313"
line-length = 88

extend-exclude = [
  ".git",
  ".venv",
  "venv",
  "build",
  "dist",
  "node_modules",
  "OLD",
  "**/examples/**",
  ".vscode",
]

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "W",   # pycodestyle warnings
  "I",   # isort
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "SIM", # flake8-simplify
  "D",   # pydocstyle (docstrings)
]
extend-ignore = [
  "E501", # handled by Black
]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]      # allow re-exports
"**/tests/**" = ["D"]            # do not enforce docstrings in tests
