name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint, format, and type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (dev)
        run: |
          poetry install --no-interaction --only dev

      - name: Run pre-commit via Poetry
        run: |
          poetry run pre-commit run --all-files

  test-engine:
    name: Test idun_agent_engine (Py3.13)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (root)
        run: |
          poetry install --no-interaction

      - name: Run tests (engine)
        env:
          PYTHONPATH: libs/idun_agent_engine/src
        run: |
          poetry run pytest -q
